name: AlpineLinux

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        tag: ['3.19','3.18','3.17','3.16']

    container: alpine:${{ matrix.tag }}

    steps:
      - run: apk update
      - run: apk add curl g++ libc-dev linux-headers

      - uses: actions/checkout@v4

      - run: ./ppkg --help
      - run: ./ppkg --version

      - run: ./ppkg setup

      - run: ./ppkg about

      - run: ./ppkg integrate zsh

      - run: ./ppkg update

      - run: ./ppkg search lib
      - run: ./ppkg search libzip


      - run: ./ppkg info-available libzip
      - run: ./ppkg info-available libzip --yaml
      - run: ./ppkg info-available libzip --json
      - run: ./ppkg info-available libzip version
      - run: ./ppkg info-available libzip license
      - run: ./ppkg info-available libzip summary
      - run: ./ppkg info-available libzip web-url
      - run: ./ppkg info-available libzip git-url
      - run: ./ppkg info-available libzip git-sha
      - run: ./ppkg info-available libzip git-ref
      - run: ./ppkg info-available libzip src-url
      - run: ./ppkg info-available libzip src-sha

      - run: ./ppkg depends libzip

      - run: ./ppkg install libzip

      - run: ./ppkg tree libzip

      - run: ./ppkg info-installed libzip installed-dir
      - run: ./ppkg info-installed libzip installed-files
      - run: ./ppkg info-available libzip version
      - run: ./ppkg info-installed libzip builtat-iso-8601-utc
      - run: ./ppkg info-installed libzip builtat-iso-8601
      - run: ./ppkg info-installed libzip builtat-rfc-3339
      - run: ./ppkg info-installed libzip builtat-iso-8601-utc
      - run: ./ppkg info-installed libzip builtat-rfc-3339-utc

      - run: ./ppkg pack libzip
      - run: ./ppkg pack libzip -t tar.gz
      - run: ./ppkg pack libzip -t tar.lz
      - run: ./ppkg pack libzip -t tar.xz
      - run: ./ppkg pack libzip -t tar.bz2
      - run: ./ppkg pack libzip -t zip

      - run: apk add alpine-sdk

      # https://wiki.alpinelinux.org/wiki/Include:Abuild-keygen
      # https://github.com/alpinelinux/abuild/blob/master/abuild-keygen.in
      - run: openssl genrsa -out leleliu008@gmail.com.rsa 2048
      - run: openssl rsa     -in leleliu008@gmail.com.rsa -pubout -out leleliu008@gmail.com.rsa.pub

      - run: cp leleliu008@gmail.com.rsa.pub /etc/apk/keys/

      - run: install -d ~/.abuild/
      - run: printf 'PACKAGER_PRIVKEY="%s"\n' "$PWD/leleliu008@gmail.com.rsa" > ~/.abuild/abuild.conf

      - run: ./ppkg export.apk libzip
      - run: ./ppkg export.apk libzip -o ~/
      - run: ./ppkg export.apk libzip -o a/b.apk

      - run: apk add a/b.apk
      - run: apk info -L libzip

      - run: |
          printf '%s\n' 'version: 1000' >> ~/.ppkg/repos.d/official-core/formula/libzip.yml

      - run: ./ppkg ls-available
      - run: ./ppkg ls-installed
      - run: ./ppkg ls-outdated

      - run: ./ppkg is-available libzip
      - run: ./ppkg is-installed libzip
      - run: ./ppkg is-outdated  libzip


      - run: ./ppkg upgrade   libzip
      - run: ./ppkg reinstall libzip
      - run: ./ppkg uninstall libzip

      - run: ./ppkg fetch curl

      - run: ./ppkg cleanup

      - run: ./ppkg upgrade-self

      - run: ./ppkg formula-repo-list

      - run: ./ppkg formula-repo-add my_repo1 https://github.com/leleliu008/ppkg-formula-repository-official-core
      - run: ./ppkg formula-repo-add my_repo2 https://github.com/leleliu008/ppkg-formula-repository-official-core --branch=master
      - run: ./ppkg formula-repo-add my_repo3 https://github.com/leleliu008/ppkg-formula-repository-official-core --unpin
      - run: ./ppkg formula-repo-add my_repo4 https://github.com/leleliu008/ppkg-formula-repository-official-core --unpin --disable

      - run: ./ppkg formula-repo-list

      - run: ./ppkg formula-repo-init my_repo10 https://github.com/leleliu008/ppkg-formula-repository-official-core
      - run: ./ppkg formula-repo-init my_repo11 https://github.com/leleliu008/ppkg-formula-repository-official-core --branch=main
      - run: ./ppkg formula-repo-init my_repo12 https://github.com/leleliu008/ppkg-formula-repository-official-core --unpin
      - run: ./ppkg formula-repo-init my_repo13 https://github.com/leleliu008/ppkg-formula-repository-official-core --unpin --disable

      - run: ./ppkg formula-repo-list

      - run: ./ppkg formula-repo-conf my_repo1 --url=https://github.com/leleliu008/ppkg-formula-repository-official-core
      - run: ./ppkg formula-repo-conf my_repo2 --branch=master --unpin
      - run: ./ppkg formula-repo-conf my_repo3 --pin
      - run: ./ppkg formula-repo-conf my_repo4 --pin --enable

      - run: ./ppkg formula-repo-list

      - run: ./ppkg formula-repo-sync my_repo2

      - run: ./ppkg formula-repo-info my_repo2

      - run: ./ppkg formula-repo-del my_repo1
