name: AlpineLinux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        tag: ['3.15','3.14','3.13','3.12']

    container: alpine:${{ matrix.tag }}

    steps:
      - run: apk update
      - run: apk add curl g++ libc-dev linux-headers

      - uses: actions/checkout@v3

      - run: ./ppkg --help
      - run: ./ppkg --version

      - run: ./ppkg setup

      - run: ./ppkg env

      - run: ./ppkg integrate zsh

      - run: ./ppkg update

      - run: ./ppkg search lib
      - run: ./ppkg search libzip

      - run: ./ppkg info libzip
      - run: ./ppkg info libzip summary
      - run: ./ppkg info libzip webpage
      - run: ./ppkg info libzip version
      - run: ./ppkg info libzip src-url
      - run: ./ppkg info libzip src-sha

      - run: ./ppkg depends libzip

      - run: ./ppkg install libzip

      - run: ./ppkg tree libzip
      - run: ./ppkg pack libzip
      - run: ./ppkg pack libzip -t tar.xz


      - run: ./ppkg ls-available
      - run: ./ppkg ls-installed
      - run: ./ppkg ls-outdated

      - run: ./ppkg is-available libzip
      - run: ./ppkg is-installed libzip
      - run: ./ppkg is-outdated  libzip || echo "not outdated"

      - run: ./ppkg uninstall libzip

      - run: ./ppkg fetch curl

      - run: ./ppkg upgrade-self

      - run: ./ppkg formula-repo-list

      - run: ./ppkg formula-repo-add my_repo1 https://github.com/leleliu008/ppkg-formula-repository-offical-core
      - run: ./ppkg formula-repo-add my_repo2 https://github.com/leleliu008/ppkg-formula-repository-offical-core --branch=master
      - run: ./ppkg formula-repo-add my_repo3 https://github.com/leleliu008/ppkg-formula-repository-offical-core --unpin
      - run: ./ppkg formula-repo-add my_repo4 https://github.com/leleliu008/ppkg-formula-repository-offical-core --unpin --disable

      - run: ./ppkg formula-repo-list

      - run: ./ppkg formula-repo-init my_repo10 https://github.com/leleliu008/ppkg-formula-repository-offical-core
      - run: ./ppkg formula-repo-init my_repo11 https://github.com/leleliu008/ppkg-formula-repository-offical-core --branch=main
      - run: ./ppkg formula-repo-init my_repo12 https://github.com/leleliu008/ppkg-formula-repository-offical-core --unpin
      - run: ./ppkg formula-repo-init my_repo13 https://github.com/leleliu008/ppkg-formula-repository-offical-core --unpin --disable

      - run: ./ppkg formula-repo-list

      - run: ./ppkg formula-repo-conf my_repo1 --url=https://github.com/leleliu008/ppkg-formula-repository-offical-core
      - run: ./ppkg formula-repo-conf my_repo2 --branch=master --unpin
      - run: ./ppkg formula-repo-conf my_repo3 --pin
      - run: ./ppkg formula-repo-conf my_repo4 --pin --enable

      - run: ./ppkg formula-repo-list

      - run: ./ppkg formula-repo-sync my_repo2

      - run: ./ppkg formula-repo-info my_repo2

      - run: ./ppkg formula-repo-del my_repo1
