name: AlpineLinux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        tag: ['3.15','3.14','3.13','3.12']

    container: alpine:${{ matrix.tag }}

    steps:
      - run: apk update
      - run: apk add curl g++ libc-dev linux-headers

      - uses: actions/checkout@v3

      - run: bin/ppkg --help
      - run: bin/ppkg --version

      - run: bin/ppkg setup

      - run: bin/ppkg env

      - run: bin/ppkg integrate zsh

      - run: bin/ppkg update

      - run: bin/ppkg search lib
      - run: bin/ppkg search libzip

      - run: bin/ppkg info libzip
      - run: bin/ppkg info libzip summary
      - run: bin/ppkg info libzip webpage
      - run: bin/ppkg info libzip version
      - run: bin/ppkg info libzip src-url
      - run: bin/ppkg info libzip src-sha

      - run: bin/ppkg depends libzip

      - run: bin/ppkg install libzip

      - run: bin/ppkg tree libzip
      - run: bin/ppkg pack libzip
      - run: bin/ppkg pack libzip -t tar.xz


      - run: bin/ppkg ls-available
      - run: bin/ppkg ls-installed
      - run: bin/ppkg ls-outdated

      - run: bin/ppkg is-available libzip
      - run: bin/ppkg is-installed libzip
      - run: bin/ppkg is-outdated  libzip || echo "not outdated"

      - run: bin/ppkg uninstall libzip

      - run: bin/ppkg fetch curl

      - run: bin/ppkg upgrade-self

      - run: bin/ppkg formula-repo-list

      - run: bin/ppkg formula-repo-add my_repo1 https://github.com/leleliu008/ppkg-formula-repository-offical-core
      - run: bin/ppkg formula-repo-add my_repo2 https://github.com/leleliu008/ppkg-formula-repository-offical-core --branch=master
      - run: bin/ppkg formula-repo-add my_repo3 https://github.com/leleliu008/ppkg-formula-repository-offical-core --unpin
      - run: bin/ppkg formula-repo-add my_repo4 https://github.com/leleliu008/ppkg-formula-repository-offical-core --unpin --disable

      - run: bin/ppkg formula-repo-list

      - run: bin/ppkg formula-repo-init my_repo10 https://github.com/leleliu008/ppkg-formula-repository-offical-core
      - run: bin/ppkg formula-repo-init my_repo11 https://github.com/leleliu008/ppkg-formula-repository-offical-core --branch=main
      - run: bin/ppkg formula-repo-init my_repo12 https://github.com/leleliu008/ppkg-formula-repository-offical-core --unpin
      - run: bin/ppkg formula-repo-init my_repo13 https://github.com/leleliu008/ppkg-formula-repository-offical-core --unpin --disable

      - run: bin/ppkg formula-repo-list

      - run: bin/ppkg formula-repo-conf my_repo1 --url=https://github.com/leleliu008/ppkg-formula-repository-offical-core
      - run: bin/ppkg formula-repo-conf my_repo2 --branch=master --unpin
      - run: bin/ppkg formula-repo-conf my_repo3 --pin
      - run: bin/ppkg formula-repo-conf my_repo4 --pin --enable

      - run: bin/ppkg formula-repo-list

      - run: bin/ppkg formula-repo-sync my_repo2

      - run: bin/ppkg formula-repo-info my_repo2

      - run: bin/ppkg formula-repo-del my_repo1
