name: AlpineLinux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        tag: ['3.15','3.14','3.13','3.12']

    container: alpine:${{ matrix.tag }}

    steps:
      - run: apk update
      - run: apk add curl g++ libc-dev linux-headers

      - uses: actions/checkout@v3

      - run: ./ppkg --help
      - run: ./ppkg --version

      - run: ./ppkg setup

      - run: ./ppkg env

      - run: ./ppkg integrate zsh

      - run: ./ppkg update

      - run: ./ppkg search lib
      - run: ./ppkg search libzip


      - run: ./ppkg info @all
      - run: ./ppkg info libzip
      - run: ./ppkg info libzip --yaml
      - run: ./ppkg info libzip --json
      - run: ./ppkg info libzip version
      - run: ./ppkg info libzip license
      - run: ./ppkg info libzip summary
      - run: ./ppkg info libzip web-url
      - run: ./ppkg info libzip git-url
      - run: ./ppkg info libzip git-sha
      - run: ./ppkg info libzip git-ref
      - run: ./ppkg info libzip src-url
      - run: ./ppkg info libzip src-sha


      - run: ./ppkg formula libzip
      - run: ./ppkg formula libzip --yaml
      - run: ./ppkg formula libzip --json
      - run: ./ppkg formula libzip version
      - run: ./ppkg formula libzip license
      - run: ./ppkg formula libzip summary
      - run: ./ppkg formula libzip web-url
      - run: ./ppkg formula libzip git-url
      - run: ./ppkg formula libzip git-sha
      - run: ./ppkg formula libzip git-ref
      - run: ./ppkg formula libzip src-url
      - run: ./ppkg formula libzip src-sha


      - run: ./ppkg depends libzip

      - run: ./ppkg install libzip

      - run: ./ppkg tree libzip


      - run: ./ppkg receipt libzip
      - run: ./ppkg receipt libzip --yaml
      - run: ./ppkg receipt libzip --json
      - run: ./ppkg receipt libzip version
      - run: ./ppkg receipt libzip license
      - run: ./ppkg receipt libzip summary
      - run: ./ppkg receipt libzip web-url
      - run: ./ppkg receipt libzip git-url
      - run: ./ppkg receipt libzip git-sha
      - run: ./ppkg receipt libzip git-ref
      - run: ./ppkg receipt libzip src-url
      - run: ./ppkg receipt libzip src-sha


      - run: ./ppkg info libzip installed-dir
      - run: ./ppkg info libzip installed-files
      - run: ./ppkg info libzip installed-version
      - run: ./ppkg info libzip installed-timestamp-unix
      - run: ./ppkg info libzip installed-timestamp-iso-8601
      - run: ./ppkg info libzip installed-timestamp-rfc-3339
      - run: ./ppkg info libzip installed-timestamp-iso-8601-utc
      - run: ./ppkg info libzip installed-timestamp-rfc-3339-utc


      - run: ./ppkg pack libzip
      - run: ./ppkg pack libzip -t tar.gz
      - run: ./ppkg pack libzip -t tar.lz
      - run: ./ppkg pack libzip -t tar.xz
      - run: ./ppkg pack libzip -t tar.bz2
      - run: ./ppkg pack libzip -t zip


      - run: |
          printf '%s\n' 'version: 1000' >> ~/.ppkg/repos.d/offical-core/formula/libzip.yml


      - run: ./ppkg ls-available
      - run: ./ppkg ls-installed
      - run: ./ppkg ls-outdated

      - run: ./ppkg is-available libzip
      - run: ./ppkg is-installed libzip
      - run: ./ppkg is-outdated  libzip


      - run: ./ppkg upgrade   libzip
      - run: ./ppkg reinstall libzip
      - run: ./ppkg uninstall libzip

      - run: ./ppkg fetch curl

      - run: ./ppkg cleanup

      - run: ./ppkg upgrade-self

      - run: ./ppkg formula-repo-list

      - run: ./ppkg formula-repo-add my_repo1 https://github.com/leleliu008/ppkg-formula-repository-offical-core
      - run: ./ppkg formula-repo-add my_repo2 https://github.com/leleliu008/ppkg-formula-repository-offical-core --branch=master
      - run: ./ppkg formula-repo-add my_repo3 https://github.com/leleliu008/ppkg-formula-repository-offical-core --unpin
      - run: ./ppkg formula-repo-add my_repo4 https://github.com/leleliu008/ppkg-formula-repository-offical-core --unpin --disable

      - run: ./ppkg formula-repo-list

      - run: ./ppkg formula-repo-init my_repo10 https://github.com/leleliu008/ppkg-formula-repository-offical-core
      - run: ./ppkg formula-repo-init my_repo11 https://github.com/leleliu008/ppkg-formula-repository-offical-core --branch=main
      - run: ./ppkg formula-repo-init my_repo12 https://github.com/leleliu008/ppkg-formula-repository-offical-core --unpin
      - run: ./ppkg formula-repo-init my_repo13 https://github.com/leleliu008/ppkg-formula-repository-offical-core --unpin --disable

      - run: ./ppkg formula-repo-list

      - run: ./ppkg formula-repo-conf my_repo1 --url=https://github.com/leleliu008/ppkg-formula-repository-offical-core
      - run: ./ppkg formula-repo-conf my_repo2 --branch=master --unpin
      - run: ./ppkg formula-repo-conf my_repo3 --pin
      - run: ./ppkg formula-repo-conf my_repo4 --pin --enable

      - run: ./ppkg formula-repo-list

      - run: ./ppkg formula-repo-sync my_repo2

      - run: ./ppkg formula-repo-info my_repo2

      - run: ./ppkg formula-repo-del my_repo1
