name: ArchLinux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    container: archlinux

    steps:
      - run: pacman -Syy --noconfirm
      - run: pacman -S   --noconfirm curl gcc

      - uses: actions/checkout@v3

      - run: ./ppkg --help
      - run: ./ppkg --version

      - run: ./ppkg setup

      - run: ./ppkg env

      - run: ./ppkg integrate zsh

      - run: ./ppkg update

      - run: ./ppkg search lib
      - run: ./ppkg search libzip

      - run: ./ppkg info-available libzip
      - run: ./ppkg info-available libzip version
      - run: ./ppkg info-available libzip web-url
      - run: ./ppkg info-available libzip src-url

      - run: ./ppkg depends libzip

      - run: ./ppkg install libzip

      - run: ./ppkg tree libzip
      - run: ./ppkg pack libzip -t tar.xz

      - run: ./ppkg formula-repo-list

      - run: ./ppkg ls-available
      - run: ./ppkg ls-installed
      - run: ./ppkg ls-outdated

      - run: ./ppkg is-available libzip
      - run: ./ppkg is-installed libzip
      - run: ./ppkg is-outdated  libzip || echo "not outdated"

      - run: ./ppkg uninstall libzip

      - run: ./ppkg fetch curl

      - run: ./ppkg upgrade-self
