name: CentOS Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        tag: ['7.5.1804', '8.3.2011']

    container: centos:${{ matrix.tag }}

    steps:
      - run: |
          if [ ${{ matrix.tag }} = '7.5.1804' ] ; then
            yum -y update
            yum -y install curl g++
          else
            sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*
            sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*

            dnf -y update
            dnf -y install curl g++
          fi

      - uses: actions/checkout@v3

      - run: bin/ppkg --help
      - run: bin/ppkg --version

      - run: bin/ppkg env

      - run: bin/ppkg setup

      - run: bin/ppkg integrate zsh

      - run: bin/ppkg update

      - run: bin/ppkg search lib
      - run: bin/ppkg search libzip

      - run: bin/ppkg info libzip
      - run: bin/ppkg info libzip version
      - run: bin/ppkg info libzip webpage
      - run: bin/ppkg info libzip src.url

      - run: bin/ppkg depends libzip

      - run: bin/ppkg install libzip

      - run: bin/ppkg tree libzip
      - run: bin/ppkg pack libzip tar.xz

      - run: bin/ppkg formula-repo list
      - run: bin/ppkg formula view curl

      - run: bin/ppkg ls-available
      - run: bin/ppkg ls-installed
      - run: bin/ppkg ls-outdated

      - run: bin/ppkg is-available libzip
      - run: bin/ppkg is-installed libzip
      - run: bin/ppkg is-outdated  libzip || echo 'not outdated'

      - run: bin/ppkg uninstall libzip

      - run: bin/ppkg fetch curl

      - run: bin/ppkg upgrade @self
