name: CentOS Linux

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        tag: [7, 8]

    container: centos:${{ matrix.tag }}

    steps:
      - run: |
            yum -y update
            yum -y install epel-release
            yum -y --enablerepo=epel update
            yum -y --enablerepo=epel install curl xz gcc-c++
        if: ${{ matrix.tag == 7 }}

      - run: |
            sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*
            sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*
            dnf -y update
            dnf -y install curl xz gcc-c++
        if: ${{ matrix.tag == 8 }}

      - uses: actions/checkout@v3

      - run: ./ppkg --help
      - run: ./ppkg --version

      - run: ./ppkg setup

      - run: ./ppkg about

      - run: ./ppkg integrate zsh

      - run: ./ppkg update

      - run: ./ppkg search lib
      - run: ./ppkg search libzip

      - run: ./ppkg info-available libzip
      - run: ./ppkg info-available libzip version
      - run: ./ppkg info-available libzip web-url
      - run: ./ppkg info-available libzip src-url

      - run: ./ppkg depends libzip

      - run: ./ppkg install libzip


      - run: ./ppkg tree libzip

      - run: ./ppkg pack libzip -t tar.xz

      - run: yum -y install rpmdevtools rpmlint
        if: ${{ matrix.tag == 7 }}

      - run: dnf -y install rpmdevtools rpmlint
        if: ${{ matrix.tag == 8 }}

      - run: ./ppkg export.rpm libzip -o ~/
      - run: ./ppkg export.rpm libzip -o a/b.rpm

      - run: rpm -i a/b.rpm
      - run: rpm -ql libzip


      - run: ./ppkg formula-repo-list

      - run: ./ppkg ls-available
      - run: ./ppkg ls-installed
      - run: ./ppkg ls-outdated

      - run: ./ppkg is-available libzip
      - run: ./ppkg is-installed libzip
      - run: ./ppkg is-outdated  libzip || echo 'not outdated'

      - run: ./ppkg uninstall libzip

      - run: ./ppkg fetch curl

      - run: ./ppkg upgrade-self
