name: DragonFlyBSD

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        dragonflybsd-version: ['6.4.0']
        pm: ['--syspm', '']

    steps:
      - uses: actions/checkout@v4

      - uses: vmactions/dragonflybsd-vm@v1
        with:
          release: "${{ matrix.version }}"
          usesh: true
          sync: rsync
          copyback: true
          run: |
            run() {
              printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
              eval "$@"
            }

            run sudo pkg install -y curl gcc

            run ./ppkg --help
            run ./ppkg --version

            run ./ppkg setup ${{ matrix.pm }}

            run ./ppkg about

            run ./ppkg integrate zsh

            run ./ppkg update

            run ./ppkg search lib
            run ./ppkg search uctags

            run ./ppkg info-available uctags
            run ./ppkg info-available uctags summary
            run ./ppkg info-available uctags web-url
            run ./ppkg info-available uctags version

            run ./ppkg depends uctags


            run ./ppkg install uctags


            run ./ppkg tree uctags
            run ./ppkg pack uctags -t tar.xz

            run ./ppkg formula-repo-list


            run ./ppkg ls-available
            run ./ppkg ls-installed
            run ./ppkg ls-outdated

            run ./ppkg is-available uctags
            run ./ppkg is-installed uctags
            run ./ppkg is-outdated uctags || echo "not outdated"

            run ./ppkg uninstall uctags

            run ./ppkg fetch curl

            run ./ppkg upgrade-self
