name: Fedora

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        tag: [34, 35, 36, 37]

    container: fedora:${{ matrix.tag }}

    steps:
      - run: dnf -y update
      - run: dnf -y install curl xz g++

      - uses: actions/checkout@v4

      - run: ./ppkg --help
      - run: ./ppkg --version

      - run: ./ppkg setup

      - run: ./ppkg env

      - run: ./ppkg integrate zsh

      - run: ./ppkg update

      - run: ./ppkg search lib
      - run: ./ppkg search libzip

      - run: ./ppkg info-available libzip
      - run: ./ppkg info-available libzip version
      - run: ./ppkg info-available libzip web-url
      - run: ./ppkg info-available libzip src-url

      - run: ./ppkg depends libzip

      - run: ./ppkg install libzip

      - run: ./ppkg tree libzip

      - run: ./ppkg pack libzip -t tar.xz

      - run: dnf install rpmdevtools

      - run: ./ppkg export.rpm libzip -o ~/
      - run: ./ppkg export.rpm libzip -o a/b.rpm

      - run: ./ppkg formula-repo-list

      - run: ./ppkg ls-available
      - run: ./ppkg ls-installed
      - run: ./ppkg ls-outdated

      - run: ./ppkg is-available libzip
      - run: ./ppkg is-installed libzip
      - run: ./ppkg is-outdated  libzip || echo "not outdated"

      - run: ./ppkg uninstall libzip

      - run: ./ppkg fetch curl

      - run: ./ppkg upgrade-self
