name: FreeBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-12

    strategy:
      fail-fast: false
      matrix:
        version: [13, 12]
    
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: vagrant-generic-freebsd-${{ matrix.version }}
          restore-keys: |
            vagrant-generic-freebsd-${{ matrix.version }}

      - uses: leleliu008/github-actions-vagrant@v1
        with:
          mem: 2048
          box: generic/freebsd${{ matrix.version }}
          run: |
            run pkg update
            run pkg install -y curl libnghttp2

            run ./ppkg --help
            run ./ppkg --version

            run ./ppkg setup --use-system-package-manager

            run ./ppkg env

            run ./ppkg integrate zsh

            run ./ppkg update

            run ./ppkg search lib
            run ./ppkg search libzip

            run ./ppkg info libzip
            run ./ppkg info libzip summary
            run ./ppkg info libzip webpage
            run ./ppkg info libzip version

            run ./ppkg depends libzip


            run ./ppkg install libzip


            run ./ppkg tree libzip
            run ./ppkg pack libzip -t tar.xz

            run ./ppkg formula-repo-list


            run ./ppkg ls-available
            run ./ppkg ls-installed
            run ./ppkg ls-outdated

            run ./ppkg is-available libzip
            run ./ppkg is-installed libzip
            run ./ppkg is-outdated libzip || echo "not outdated"

            run ./ppkg uninstall libzip

            run ./ppkg fetch curl

            run ./ppkg upgrade-self
