name: FreeBSD

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        freebsd-version: ['14.1', '14.0', '13.3', '13.2']

    steps:
      - uses: actions/checkout@v4

      - uses: cross-platform-actions/action@v0.25.0
        with:
          operating_system: freebsd
          version: ${{ matrix.freebsd-version }}
          shell: bash
          run: |
            run() {
              printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
              eval "$@"
            }

            run sudo pkg install -y curl libnghttp2 gcc

            run ./ppkg --help
            run ./ppkg --version

            run ./ppkg setup

            run ./ppkg about

            run ./ppkg integrate zsh

            run ./ppkg update

            run ./ppkg search lib
            run ./ppkg search libzip

            run ./ppkg info-available libzip
            run ./ppkg info-available libzip summary
            run ./ppkg info-available libzip web-url
            run ./ppkg info-available libzip version

            run ./ppkg depends libzip


            run ./ppkg install libzip


            run ./ppkg tree libzip
            run ./ppkg pack libzip -t tar.xz

            run ./ppkg formula-repo-list


            run ./ppkg ls-available
            run ./ppkg ls-installed
            run ./ppkg ls-outdated

            run ./ppkg is-available libzip
            run ./ppkg is-installed libzip
            run ./ppkg is-outdated libzip || echo "not outdated"

            run ./ppkg uninstall libzip

            run ./ppkg fetch curl

            run ./ppkg upgrade-self
