name: macOS

on:
  push:
    branches: [ master, dev, tmp ]
  pull_request:
    branches: [ master, dev, tmp ]

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        version: [15, 14, 13]

    runs-on: macos-${{ matrix.version }}

    steps:
      - uses: actions/checkout@v4

      - run: ./ppkg --help
      - run: ./ppkg --version

      - run: ./ppkg -h
      - run: ./ppkg -V

      - run: ./ppkg setup

      - run: ./ppkg about

      - run: ./ppkg integrate zsh

      - run: ./ppkg update

      - run: ./ppkg search lib
      - run: ./ppkg search uctags

      - run: ./ppkg info-available uctags
      - run: ./ppkg info-available uctags summary
      - run: ./ppkg info-available uctags web-url
      - run: ./ppkg info-available uctags version

      - run: ./ppkg depends uctags

      - run: ./ppkg install uctags

      - run: ./ppkg tree uctags

      - run: ./ppkg bundle uctags .tar.gz
      - run: ./ppkg bundle uctags .tar.xz
      - run: ./ppkg bundle uctags .tar.bz2
      - run: ./ppkg bundle uctags .zip

      - run: ./ppkg formula-repo-list

      - run: ./ppkg ls-available
      - run: ./ppkg ls-installed
      - run: ./ppkg ls-outdated

      - run: ./ppkg is-available uctags
      - run: ./ppkg is-installed uctags
      - run: ./ppkg is-symlinked uctags || echo "not symlinked"
      - run: ./ppkg is-outdated  uctags || echo "not outdated"

      - run: ./ppkg info-installed uctags installed-dir
      - run: ./ppkg info-installed uctags installed-files
      - run: ./ppkg info-installed uctags builtat
      - run: ./ppkg info-installed uctags builtat-rfc-3339-utc
      - run: ./ppkg info-installed uctags builtat-iso-8601-utc
      - run: ./ppkg info-installed uctags builtat-rfc-3339
      - run: ./ppkg info-installed uctags builtat-iso-8601

      - run: ./ppkg uninstall uctags

      - run: ./ppkg fetch curl

      - run: ./ppkg upgrade-self
