name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        version: [12, 11]

    runs-on: macos-${{ matrix.version }}

    steps:
      - uses: actions/checkout@v3

      - run: ./ppkg --help
      - run: ./ppkg --version

      - run: ./ppkg -h
      - run: ./ppkg -V

      - run: ./ppkg setup

      - run: ./ppkg env

      - run: ./ppkg integrate zsh

      - run: ./ppkg update

      - run: ./ppkg search lib
      - run: ./ppkg search libzip

      - run: ./ppkg info-available libzip
      - run: ./ppkg info-available libzip summary
      - run: ./ppkg info-available libzip web-url
      - run: ./ppkg info-available libzip version

      - run: ./ppkg depends libzip

      - run: ./ppkg install libzip

      - run: ./ppkg tree libzip

      - run: ./ppkg pack libzip -t tar.gz
      - run: ./ppkg pack libzip -t tar.xz
      - run: ./ppkg pack libzip -t tar.bz2
      - run: ./ppkg pack libzip -t zip

      - run: ./ppkg formula-repo-list

      - run: ./ppkg ls-available
      - run: ./ppkg ls-installed
      - run: ./ppkg ls-symlinked
      - run: ./ppkg ls-outdated

      - run: ./ppkg is-available libzip
      - run: ./ppkg is-installed libzip
      - run: ./ppkg is-symlinked libzip || echo "not symlinked"
      - run: ./ppkg is-outdated  libzip || echo "not outdated"

      - run: ./ppkg info-installed libzip installed-dir
      - run: ./ppkg info-installed libzip installed-files
      - run: ./ppkg info-installed libzip builtat
      - run: ./ppkg info-installed libzip builtat-rfc-3339-utc
      - run: ./ppkg info-installed libzip builtat-iso-8601-utc
      - run: ./ppkg info-installed libzip builtat-rfc-3339
      - run: ./ppkg info-installed libzip builtat-iso-8601

      - run: ./ppkg uninstall libzip

      - run: ./ppkg fetch curl

      - run: ./ppkg upgrade-self
