name: LinuxMint

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        tag: [21.3, 20.1]

    container: linuxmintd/mint${{ matrix.tag }}-amd64

    steps:
      - run: apt -y update
      - run: apt -y install curl g++

      - uses: actions/checkout@v4

      - run: ./ppkg --help
      - run: ./ppkg --version

      - run: ./ppkg setup

      - run: ./ppkg about

      - run: ./ppkg integrate zsh

      - run: ./ppkg update

      - run: ./ppkg search lib
      - run: ./ppkg search uctags

      - run: ./ppkg info-available uctags
      - run: ./ppkg info-available uctags version
      - run: ./ppkg info-available uctags web-url
      - run: ./ppkg info-available uctags src-url

      - run: ./ppkg depends uctags

      - run: ./ppkg install uctags

      - run: ./ppkg pack uctags -t tar.gz
      - run: ./ppkg pack uctags -t tar.xz
      - run: ./ppkg pack uctags -t tar.bz2
      - run: ./ppkg pack uctags -t zip

      - run: ./ppkg export.deb uctags
      - run: ./ppkg export.deb uctags -o ~/
      - run: ./ppkg export.deb uctags -o a/b.deb

      - run: dpkg -i a/b.deb
      - run: dpkg -L uctags

      - run: ./ppkg formula-repo-list

      - run: ./ppkg ls-available
      - run: ./ppkg ls-installed
      - run: ./ppkg ls-outdated

      - run: ./ppkg is-available uctags
      - run: ./ppkg is-installed uctags
      - run: ./ppkg is-outdated  uctags || echo "not outdated"

      - run: ./ppkg uninstall uctags

      - run: ./ppkg fetch curl

      - run: ./ppkg upgrade-self
