name: MSYS2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        msystem: [MSYS, MINGW32, MINGW64]

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: git

      - run: git config --global core.autocrlf input
        shell: bash

      - uses: actions/checkout@v2

      - run: bin/zpkg --help
      - run: bin/zpkg --version


      - run: bin/zpkg env

      - run: bin/zpkg integrate zsh

      - run: bin/zpkg update

      - run: bin/zpkg search lib
      - run: bin/zpkg search base64

      - run: bin/zpkg info base64
      - run: bin/zpkg info base64 version
      - run: bin/zpkg info base64 webpage
      - run: bin/zpkg info base64

      - run: bin/zpkg depends base64

      - run: bin/zpkg homepage
      - run: bin/zpkg homepage base64

      - run: bin/zpkg install base64

      - run: bin/zpkg prefix
      - run: bin/zpkg prefix base64

      - run: bin/zpkg tree base64
      - run: bin/zpkg pack base64

      - run: bin/zpkg formula-repo list
      - run: bin/zpkg formula view curl


      - run: bin/zpkg ls-available
      - run: bin/zpkg ls-installed
      - run: bin/zpkg ls-outdated

      - run: bin/zpkg is-available base64
      - run: bin/zpkg is-installed base64
      - run: bin/zpkg is-outdated base64 || echo "not outdated"

      - run: bin/zpkg uninstall base64

      - run: bin/zpkg fetch curl

      - run: bin/zpkg upgrade @self
