name: NetBSD

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        netbsd-version: ['10.0', '9.4', '9.3', '9.2']
        pm: ['--syspm', '']

    steps:
      - uses: actions/checkout@v4

      - run: curl -LO https://curl.se/ca/cacert.pem

      - uses: cross-platform-actions/action@v0.25.0
        with:
          operating_system: netbsd
          version: ${{ matrix.netbsd-version }}
          shell: bash
          run: |
            run() {
              printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
              eval "$@"
            }

            #run sudo pkgin -y update
            #run sudo pkgin -y install llvm

            run export SSL_CERT_FILE="$PWD/cacert.pem"

            run ./ppkg --help
            run ./ppkg --version

            run ./ppkg setup ${{ matrix.pm }}

            run ./ppkg about

            run ./ppkg integrate zsh

            run ./ppkg update

            run ./ppkg search lib
            run ./ppkg search libzip

            run ./ppkg info-available libzip
            run ./ppkg info-available libzip summary
            run ./ppkg info-available libzip web-url
            run ./ppkg info-available libzip version

            run ./ppkg depends libzip

            run ./ppkg install libzip

            run ./ppkg tree libzip

            run ./ppkg pack libzip -t tar.xz

            run ./ppkg formula-repo-list

            run ./ppkg ls-available
            run ./ppkg ls-installed
            run ./ppkg ls-outdated

            run ./ppkg is-available libzip
            run ./ppkg is-installed libzip
            run ./ppkg is-outdated libzip || echo "not outdated"

            run ./ppkg uninstall libzip

            run ./ppkg fetch curl

            run ./ppkg upgrade-self
