name: OpenBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-12
    
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: vagrant-generic-openbsd-7
          restore-keys: |
            vagrant-generic-openbsd-7

      - uses: leleliu008/github-actions-vagrant@main
        with:
          mem: 2048
          box: generic/openbsd7
          box-version: 4.2.16
          run: |
            run sudo pkg_add curl gtar-- gcc%11

            run sudo ln -s /usr/local/bin/gtar /usr/bin/tar

            run ./ppkg --help
            run ./ppkg --version

            run ./ppkg setup

            run ./ppkg env

            run ./ppkg integrate zsh

            run ./ppkg update

            run ./ppkg search lib
            run ./ppkg search libzip

            run ./ppkg info libzip
            run ./ppkg info libzip summary
            run ./ppkg info libzip web-url
            run ./ppkg info libzip version

            run ./ppkg depends libzip


            run ./ppkg install libzip --jobs=1


            run ./ppkg tree libzip
            run ./ppkg pack libzip -t tar.xz

            run ./ppkg formula-repo-list


            run ./ppkg ls-available
            run ./ppkg ls-installed
            run ./ppkg ls-outdated

            run ./ppkg is-available libzip
            run ./ppkg is-installed libzip
            run ./ppkg is-outdated libzip || echo "not outdated"

            run ./ppkg uninstall libzip

            run ./ppkg fetch curl

            run ./ppkg upgrade-self
