name: openSUSE Leap

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        tag: [15.1, 15.2]

    container: opensuse/leap:${{ matrix.tag }}

    steps:
      - run: zypper update -y
      - run: zypper install -y curl tar gzip xz gcc-c++

      - uses: actions/checkout@v3

      - run: ./ppkg --help
      - run: ./ppkg --version

      - run: ./ppkg setup

      - run: ./ppkg env

      - run: ./ppkg integrate zsh

      - run: ./ppkg update

      - run: ./ppkg search lib
      - run: ./ppkg search libzip

      - run: ./ppkg info libzip
      - run: ./ppkg info libzip version
      - run: ./ppkg info libzip webpage
      - run: ./ppkg info libzip src-url

      - run: ./ppkg depends libzip

      - run: ./ppkg install libzip

      - run: ./ppkg tree libzip
      - run: ./ppkg pack libzip -t tar.xz

      - run: ./ppkg formula-repo-list

      - run: ./ppkg ls-available
      - run: ./ppkg ls-installed
      - run: ./ppkg ls-outdated

      - run: ./ppkg is-available libzip
      - run: ./ppkg is-installed libzip
      - run: ./ppkg is-outdated  libzip || echo "not outdated"

      - run: ./ppkg uninstall libzip

      - run: ./ppkg fetch curl

      - run: ./ppkg upgrade-self
