name: publish

on:
  workflow_dispatch:
    #schedule:
    #- cron: '0 1 * * *'

jobs:
  publish:

    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v3

      - run: |
          RELEASE_VERSION="$(./ppkg --version)"

          install -d "ppkg-$RELEASE_VERSION/bin/"
          install -d "ppkg-$RELEASE_VERSION/share/zsh/vendor-completions/"

          cp ppkg "ppkg-$RELEASE_VERSION/bin/ppkg"
          cp ppkg-zsh-completion "ppkg-$RELEASE_VERSION/share/zsh/vendor-completions/_ppkg"

          RELEASE_FILE_NAME="ppkg-$RELEASE_VERSION.tar.gz"

          tar zvcf "$RELEASE_FILE_NAME" "ppkg-$RELEASE_VERSION"

          SHA256SUM="$(sha256sum "$RELEASE_FILE_NAME")"

          cat > notes.md <<EOF
          sha256sum:
          \`\`\`
          $SHA256SUM
          \`\`\`
          EOF

          gh release create "$RELEASE_VERSION" "$RELEASE_FILE_NAME" --title "$RELEASE_VERSION" --notes-file notes.md
