name: Rocky Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tag: ['8', '9']

    container: rockylinux:${{ matrix.tag }}

    steps:
      - run: dnf -y update
      - run: dnf -y install xz gcc-c++
      - run:  |
          command -v curl > /dev/null || dnf -y install curl
          #https://bugs.launchpad.net/tripleo/+bug/1953156

      - uses: actions/checkout@v3


      - run: ./ppkg

      - run: ./ppkg --help
      - run: ./ppkg -h

      - run: ./ppkg --version
      - run: ./ppkg -V

      - run: ./ppkg setup -v

      - run: ./ppkg env
      - run: ./ppkg env -v

      - run: ./ppkg integrate zsh
      - run: ./ppkg integrate zsh -v

      - run: ./ppkg update

      - run: ./ppkg search lib
      - run: ./ppkg search zip

      - run: ./ppkg info @all
      - run: ./ppkg info libzip
      - run: ./ppkg info libzip --yaml
      - run: ./ppkg info libzip --json
      - run: ./ppkg info libzip version
      - run: ./ppkg info libzip license
      - run: ./ppkg info libzip summary
      - run: ./ppkg info libzip web-url
      - run: ./ppkg info libzip git-url
      - run: ./ppkg info libzip git-sha
      - run: ./ppkg info libzip git-ref
      - run: ./ppkg info libzip src-url
      - run: ./ppkg info libzip src-sha




      - run: ./ppkg depends libzip
      - run: ./ppkg depends libzip -t dot
      - run: ./ppkg depends libzip -t box
      - run: ./ppkg depends libzip -t dot -o .
      - run: ./ppkg depends libzip -t box -o .
      - run: ./ppkg depends libzip -o a/
      - run: ./ppkg depends libzip -o b/
      - run: ./ppkg depends libzip -o a.dot
      - run: ./ppkg depends libzip -o b.box

      - run: ./ppkg fetch gzip
      - run: ./ppkg fetch gsed -v

      - run: ./ppkg install libzip

      - run: ./ppkg tree libzip




      - run: ./ppkg info libzip installed-dir
      - run: ./ppkg info libzip installed-files
      - run: ./ppkg info libzip installed-version
      - run: ./ppkg info libzip installed-timestamp-unix
      - run: ./ppkg info libzip installed-timestamp-iso-8601
      - run: ./ppkg info libzip installed-timestamp-rfc-3339
      - run: ./ppkg info libzip installed-timestamp-iso-8601-utc
      - run: ./ppkg info libzip installed-timestamp-rfc-3339-utc


      - run: ./ppkg pack libzip
      - run: ./ppkg pack libzip -t tar.gz
      - run: ./ppkg pack libzip -t tar.lz
      - run: ./ppkg pack libzip -t tar.xz
      - run: ./ppkg pack libzip -t tar.bz2
      - run: ./ppkg pack libzip -t zip


      - run: |
          printf '%s\n' 'version: 1000' >> ~/.ppkg/repos.d/offical-core/formula/libzip.yml


      - run: ./ppkg ls-available
      - run: ./ppkg ls-installed
      - run: ./ppkg ls-outdated

      - run: ./ppkg is-available libzip
      - run: ./ppkg is-installed libzip
      - run: ./ppkg is-outdated  libzip

      - run: ./ppkg upgrade   libzip
      - run: ./ppkg reinstall libzip
      - run: ./ppkg uninstall libzip

      - run: ./ppkg formula-repo-list
      - run: ./ppkg formula-repo-add my_repo https://github.com/leleliu008/ppkg-formula-repository-offical-core
      - run: ./ppkg formula-repo-del my_repo

      - run: ./ppkg cleanup

      - run: ./ppkg upgrade-self
