name: Rocky Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tag: ['8', '8.5']

    container: rockylinux:${{ matrix.tag }}

    steps:
      - run: dnf -y update
      - run: dnf -y install curl xz gcc-c++

      - uses: actions/checkout@v3


      - run: bin/ppkg

      - run: bin/ppkg --help
      - run: bin/ppkg -h

      - run: bin/ppkg --version
      - run: bin/ppkg -V

      - run: bin/ppkg setup -v

      - run: bin/ppkg env
      - run: bin/ppkg env -v

      - run: bin/ppkg integrate zsh
      - run: bin/ppkg integrate zsh -v

      - run: bin/ppkg update

      - run: bin/ppkg search lib
      - run: bin/ppkg search zip

      - run: bin/ppkg info @all
      - run: bin/ppkg info libzip
      - run: bin/ppkg info libzip formula-path
      - run: bin/ppkg info libzip formula-yaml
      - run: bin/ppkg info libzip formula-json
      - run: bin/ppkg info libzip summary
      - run: bin/ppkg info libzip version
      - run: bin/ppkg info libzip license
      - run: bin/ppkg info libzip web-url
      - run: bin/ppkg info libzip git-url
      - run: bin/ppkg info libzip git-sha
      - run: bin/ppkg info libzip git-ref
      - run: bin/ppkg info libzip src-url
      - run: bin/ppkg info libzip src-sha

      - run: bin/ppkg depends libzip
      - run: bin/ppkg depends libzip --format=dot
      - run: bin/ppkg depends libzip --format=box

      - run: bin/ppkg fetch gzip
      - run: bin/ppkg fetch gsed -v

      - run: bin/ppkg install libzip

      - run: bin/ppkg tree libzip

      - run: bin/ppkg info libzip installed-dir
      - run: bin/ppkg info libzip installed-files
      - run: bin/ppkg info libzip receipt-path
      - run: bin/ppkg info libzip receipt-json
      - run: bin/ppkg info libzip receipt-yaml
      - run: bin/ppkg info libzip installed-timestamp-unix
      - run: bin/ppkg info libzip installed-timestamp-iso-8601
      - run: bin/ppkg info libzip installed-timestamp-rfc-3339
      - run: bin/ppkg info libzip installed-timestamp-iso-8601-utc
      - run: bin/ppkg info libzip installed-timestamp-rfc-3339-utc
      - run: bin/ppkg info libzip installed-version

      - run: bin/ppkg pack libzip
      - run: bin/ppkg pack libzip --type=tar.gz
      - run: bin/ppkg pack libzip --type=tar.lz
      - run: bin/ppkg pack libzip --type=tar.xz
      - run: bin/ppkg pack libzip --type=tar.bz2
      - run: bin/ppkg pack libzip --type=zip

      - run: |
          printf '%s\n' 'version: 1000' >> ~/.ppkg/repos.d/offical-core/formula/libzip.yml

      - run: bin/ppkg ls-available
      - run: bin/ppkg ls-installed
      - run: bin/ppkg ls-outdated

      - run: bin/ppkg is-available libzip
      - run: bin/ppkg is-installed libzip
      - run: bin/ppkg is-outdated  libzip

      - run: bin/ppkg upgrade   libzip
      - run: bin/ppkg reinstall libzip
      - run: bin/ppkg uninstall libzip

      - run: bin/ppkg formula-repo-list
      - run: bin/ppkg formula-repo-add my_repo https://github.com/leleliu008/ppkg-formula-repository-offical-core
      - run: bin/ppkg formula-repo-del my_repo

      - run: bin/ppkg cleanup

      - run: bin/ppkg upgrade-self
