name: version-compare

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  schedule:
    - cron: '0 20 * * *'

jobs:
  schedule:

    runs-on: macos-latest

    steps:
      - run: brew update
      - run: brew uninstall go@1.17
      - run: brew install --overwrite python@3.10 python@3.11

      - uses: actions/checkout@v3

      - run: bin/ppkg --help
      - run: bin/ppkg setup --use-system-package-manager
      - run: bin/ppkg env
      - run: bin/ppkg update
      - run: git -C ~/.ppkg/repos.d/offical-core checkout ${{ github.ref_name }}
      - run: bin/ppkg compare-versions brew
