name: VoidLinux-musl

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    container: voidlinux/voidlinux-musl

    steps:
      # SSL certificate subject doesn't match host alpha.de.repo.voidlinux.org
      # ERROR: [reposync] failed to fetch file `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata': Operation not permitted
      - run: sed -i s/alpha.de.repo.voidlinux.org/repo-default.voidlinux.org/g /usr/share/xbps.d/*

      - run: xbps-install -Syu xbps
      - run: xbps-install -S
      - run: xbps-install -Syu curl xz git gcc

      - run: git config --global --add safe.directory /__w/ppkg/ppkg
      - run: git init
      - run: git remote add origin https://github.com/${{github.repository}}
      - run: git config --local gc.auto 0
      - run: git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +${{github.sha}}:refs/remotes/origin/master
      - run: git checkout --progress --force -B master refs/remotes/origin/master
      - run: ls

      - run: ./ppkg --help
      - run: ./ppkg --version

      - run: ./ppkg setup

      - run: ./ppkg env

      - run: ./ppkg integrate zsh

      - run: ./ppkg update

      - run: ./ppkg search lib
      - run: ./ppkg search libzip

      - run: ./ppkg info libzip
      - run: ./ppkg info libzip summary
      - run: ./ppkg info libzip web-url
      - run: ./ppkg info libzip version

      - run: ./ppkg depends libzip


      - run: ./ppkg install libzip


      - run: ./ppkg tree libzip
      - run: ./ppkg pack libzip -t tar.xz

      - run: ./ppkg formula-repo-list


      - run: ./ppkg ls-available
      - run: ./ppkg ls-installed
      - run: ./ppkg ls-outdated

      - run: ./ppkg is-available libzip
      - run: ./ppkg is-installed libzip
      - run: ./ppkg is-outdated libzip || echo "not outdated"

      - run: ./ppkg uninstall libzip

      - run: ./ppkg fetch curl

      - run: ./ppkg upgrade-self
