name: VoidLinux-glibc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    container: voidlinux/voidlinux

    steps:
      # SSL certificate subject doesn't match host alpha.de.repo.voidlinux.org
      # ERROR: [reposync] failed to fetch file `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata': Operation not permitted
      - run: sed -i s/alpha.de.repo.voidlinux.org/repo-default.voidlinux.org/g /usr/share/xbps.d/*

      - run: xbps-install -Syu xbps
      - run: xbps-install -S
      - run: xbps-install -Syu curl xz gcc

      - uses: actions/checkout@v3

      - run: ./ppkg --help
      - run: ./ppkg --version

      - run: ./ppkg setup

      - run: ./ppkg env

      - run: ./ppkg integrate zsh

      - run: ./ppkg update

      - run: ./ppkg search lib
      - run: ./ppkg search libzip

      - run: ./ppkg info libzip
      - run: ./ppkg info libzip summary
      - run: ./ppkg info libzip web-url
      - run: ./ppkg info libzip version

      - run: ./ppkg depends libzip


      - run: ./ppkg install libzip


      - run: ./ppkg tree libzip
      - run: ./ppkg pack libzip -t tar.xz

      - run: ./ppkg formula-repo-list


      - run: ./ppkg ls-available
      - run: ./ppkg ls-installed
      - run: ./ppkg ls-outdated

      - run: ./ppkg is-available libzip
      - run: ./ppkg is-installed libzip
      - run: ./ppkg is-outdated libzip || echo "not outdated"

      - run: ./ppkg uninstall libzip

      - run: ./ppkg fetch curl

      - run: ./ppkg upgrade-self
